# Generated by Django 5.1.15 on 2026-05-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identificador interno del flag, en MAYÚSCULAS (ej: WEATHER).', max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Desactiva para ocultar el módulo sin borrar el flag.')),
                ('description', models.TextField(blank=True, help_text='Descripción del módulo que controla este flag.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
    ]
