# Generated by Django 5.1.15 on 2026-04-08 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organization_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_treatment_created', models.BooleanField(default=True, help_text='Recibir notificación cuando se cree un nuevo tratamiento', verbose_name='Nuevo tratamiento')),
                ('notify_treatment_finished', models.BooleanField(default=True, help_text='Recibir notificación cuando se finalice un tratamiento', verbose_name='Tratamiento finalizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
            },
        ),
    ]
