# Generated by Django 5.1.15 on 2026-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='notify_treatment_created',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='notify_treatment_finished',
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='treatment_created_channel',
            field=models.CharField(choices=[('none', 'Ninguna'), ('inbox', 'Sólo inbox'), ('email', 'Sólo email'), ('both', 'Inbox y email')], default='inbox', help_text='Recibir notificación cuando se cree un nuevo tratamiento', max_length=10, verbose_name='Nuevo tratamiento'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='treatment_finished_channel',
            field=models.CharField(choices=[('none', 'Ninguna'), ('inbox', 'Sólo inbox'), ('email', 'Sólo email'), ('both', 'Inbox y email')], default='inbox', help_text='Recibir notificación cuando se finalice un tratamiento', max_length=10, verbose_name='Tratamiento finalizado'),
        ),
    ]
