"""
Django settings for agrogest project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
import sentry_sdk
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = load_dotenv(os.path.join(BASE_DIR, '.env'))
load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'farm',
    'django_filters',
    'django_bootstrap5',
    'widget_tweaks',
    'whitenoise.runserver_nostatic',
    'mathfilters',
    'django.contrib.humanize',
    'storages',
    'watchman',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'accounts.middleware.UserTrackingMiddleware',
    # debug toolbar middleware added conditionally below

]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = 'agrogest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'farm.context_processors.sidebar_state',
                'farm.context_processors.active_nav',
                'farm.context_processors.ai_configured',
                'farm.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'agrogest.wsgi.app'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# Note: Django modules for using databases are not support in serverless
# environments like Vercel. You can use a database over HTTP, hosted elsewhere.

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:////' + (BASE_DIR / 'db.sqlite3').__str__(),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_L10N = True
USE_I18N = True
DATE_INPUT_FORMATS = ('%d/%m/%Y',)
DATE_FORMAT = 'd/m/Y'

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles", "static")
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ── Cloudflare R2 en producción, Whitenoise en local ─────────────────────────
_R2_ACCOUNT_ID = os.environ.get("CLOUDFLARE_R2_ACCOUNT_ID", "")
_R2_ACCESS_KEY_ID = os.environ.get("CLOUDFLARE_R2_ACCESS_KEY_ID", "")
_R2_SECRET_KEY = os.environ.get("CLOUDFLARE_R2_SECRET_ACCESS_KEY", "")
_R2_BUCKET_NAME = os.environ.get("CLOUDFLARE_R2_STATICS_BUCKET_NAME", "")
_R2_PUBLIC_URL = os.environ.get("CLOUDFLARE_R2_STATICS_PUBLIC_URL", "")  # ej: https://static.tudominio.com

if not DEBUG and _R2_ACCOUNT_ID and _R2_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = _R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = _R2_SECRET_KEY
    AWS_STORAGE_BUCKET_NAME = _R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = f"https://{_R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    AWS_S3_REGION_NAME = "auto"  # R2 no usa regiones reales
    AWS_DEFAULT_ACL = None  # R2 no usa ACLs
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False  # URLs públicas sin firma
    AWS_S3_OBJECT_PARAMETERS = {
        # 1 año de caché — seguro porque el nombre del fichero lleva hash de contenido
        "CacheControl": "public, max-age=31536000, immutable",
    }

    # URL base desde la que el navegador carga los estáticos.
    # Si tienes dominio custom en Cloudflare úsalo, si no pon la URL pub-xxx.r2.dev
    # que Cloudflare te da al activar "Public Access" en el bucket.
    if not _R2_PUBLIC_URL:
        raise ValueError(
            "CLOUDFLARE_R2_PUBLIC_URL no está configurada. "
            "Activa 'Public Access' en el bucket R2 y copia la URL pub-xxx.r2.dev"
        )
    STATIC_URL = _R2_PUBLIC_URL.rstrip("/") + "/"
    _r2_public_domain = _R2_PUBLIC_URL.rstrip("/").removeprefix("https://").removeprefix("http://")
    AWS_S3_CUSTOM_DOMAIN = _r2_public_domain  # ej: pub-da47fb....r2.dev

    # S3ManifestStaticFilesStorage = S3Boto3Storage + ManifestStaticFilesStorage
    # → sube a R2 y añade hash al nombre de cada fichero (cache busting automático)
    STORAGES = {
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3ManifestStaticStorage",
        },
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
    }
else:
    # Desarrollo local: Whitenoise
    STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = ''
LOGOUT_REDIRECT_URL = '/'

# ── Email ─────────────────────────────────────────────────────────────────────
# En desarrollo imprime los emails en consola; en producción usa SMTP.
# Variables de entorno necesarias en producción:
#   EMAIL_HOST, EMAIL_PORT, EMAIL_USE_TLS, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD
EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
    if DEBUG else
    'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'AgroGest <noreply@agrogest.app>')
# Tiempo de validez del enlace de recuperación de contraseña (en segundos). Por defecto: 1 día.
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', str(60 * 60 * 24)))

# Resend (email transaccional). Si se configura, tiene prioridad sobre SMTP.
# Obtén tu API key en https://resend.com
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')

# URL pública de la app (usada para construir enlaces absolutos en emails)
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# ── Asistente IA (Google Gemini) ──────────────────────────────────────────────
# Obtén tu clave GRATIS en: https://aistudio.google.com/apikey
# Modelo: gemini-flash-lite-latest → alias siempre actualizado al Flash Lite más reciente (FREE TIER)
# GEMINI_DAILY_LIMIT: límite diario de peticiones por organización (protección extra).
#   Por defecto 50 (bien por debajo de los límites gratuitos de Gemini). Ponlo a 0 para sin límite.
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-flash-lite-latest")

AEMET_API_KEY = os.environ.get("AEMET_API_KEY", "")
GEMINI_DAILY_LIMIT = int(os.environ.get("GEMINI_DAILY_LIMIT", "50"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        'faker': {
            "level": 'WARNING',
            "handlers": ["console"],
            "propagate": False,
        },
        'factory': {
            "level": 'WARNING',
            "handlers": ["console"],
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
        "propagate": True,
    },
}

SENTRY_DSN = os.getenv("SENTRY_DSN")
if not DEBUG:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        # Enable sending logs to Sentry
        enable_logs=True,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        # Set profile_session_sample_rate to 1.0 to profile 100%
        # of profile sessions.
        profile_session_sample_rate=1.0,
        # Set profile_lifecycle to "trace" to automatically
        # run the profiler on when there is an active transaction
        profile_lifecycle="trace",
    )

# Añadir debug_toolbar si está disponible y si estamos en DEBUG
import importlib

if DEBUG and importlib.util.find_spec('debug_toolbar') is not None:
    INSTALLED_APPS.append('debug_toolbar')
    # Insert middleware lo más arriba posible para que funcione correctamente
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
