# Generated by Django 5.0.11 on 2025-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_producttype_product_comments_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('spraying', 'Pulverización'), ('fertigation', 'Fertirrigación')], max_length=20),
        ),
    ]
