# Generated by Django 5.0.11 on 2025-04-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fertigation_dose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fertigation_dose_type',
            field=models.CharField(blank=True, choices=[('l_per_ha', 'L/ha'), ('kg_per_ha', 'kg/ha')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spraying_dose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spraying_dose_type',
            field=models.CharField(blank=True, choices=[('l_per_1000l', 'L/1000L agua'), ('kg_per_1000l', 'kg/1000L agua'), ('l_per_ha', 'L/ha'), ('pct', '%')], max_length=20, null=True),
        ),
    ]
