# Generated by Django 5.0.11 on 2025-04-02 18:23

from django.db import migrations


def migrate_product_data(apps, schema_editor):
    Product = apps.get_model('farm', 'Product')

    for product in Product.objects.all():
        original_dose_type = product.dose_type

        # For products with spraying-compatible dose types
        if original_dose_type in ['l_per_1000l', 'kg_per_1000l', 'l_per_ha', 'pct']:
            product.spraying_dose = product.dose
            product.spraying_dose_type = original_dose_type

        # For products with fertigation-compatible dose types
        if original_dose_type in ['kg_per_ha', 'l_per_ha']:
            product.fertigation_dose = product.dose
            product.fertigation_dose_type = original_dose_type

        product.save()


def reverse_migrate_product_data(apps, schema_editor):
    # Código para revertir los cambios si es necesario
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('farm', '0013_product_fertigation_dose_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_product_data, reverse_migrate_product_data),
    ]
