# Generated by Django 5.0.11 on 2025-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_auto_20250402_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dose_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='spraying_dose_type',
            field=models.CharField(blank=True, choices=[('l_per_1000l', 'L/1000L agua'), ('kg_per_1000l', 'kg/1000L agua'), ('pct', '%')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='taskproduct',
            name='dose_type',
            field=models.CharField(max_length=20),
        ),
    ]
