# Generated by Django 5.0.11 on 2025-04-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_remove_product_dose_remove_product_dose_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='water_per_ha',
            field=models.FloatField(blank=True, help_text='Litros de agua por hectárea', null=True),
        ),
    ]
