# Generated by Django 5.0.11 on 2025-04-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_alter_task_water_per_ha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='water_per_ha',
            field=models.IntegerField(blank=True, help_text='Litros de agua por hectárea', null=True),
        ),
    ]
