# Generated by Django 5.0.11 on 2025-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_alter_taskproduct_dose_alter_taskproduct_total_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spraying_dose_type',
            field=models.CharField(blank=True, choices=[('l_per_1000l', 'L/1000L agua'), ('kg_per_1000l', 'kg/1000L agua'), ('kg_per_ha', 'kg/ha'), ('l_per_ha', 'L/ha'), ('pct', '%')], max_length=20, null=True),
        ),
    ]
