# Generated by Django 5.0.11 on 2025-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_alter_product_spraying_dose_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('delayed', 'Atrasada')], default='pending', max_length=20),
        ),
    ]
