# Generated by Django 5.0.11 on 2025-04-09 07:56

from django.db import migrations
from django.utils import timezone


def populate_task_status(apps, schema_editor):
    Task = apps.get_model('farm', 'Task')
    today = timezone.now().date()

    # Actualizar tareas completadas
    Task.objects.filter(finish_date__isnull=False).update(status='completed')

    # Actualizar tareas atrasadas
    Task.objects.filter(
        finish_date__isnull=True,
        date__lt=today
    ).update(status='delayed')

    # Las demás quedan como pendientes (ya es el valor por defecto)


class Migration(migrations.Migration):
    dependencies = [
        ('farm', '0020_task_status'),
    ]

    operations = [
        migrations.RunPython(populate_task_status),
    ]
