# Generated by Django 5.0.11 on 2025-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_auto_20250409_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskproduct',
            old_name='task',
            new_name='treatment',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('delayed', 'Atrasado')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='taskproduct',
            unique_together={('treatment', 'product')},
        ),
    ]
