# Generated by Django 5.0.11 on 2025-04-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_rename_task_taskproduct_treatment_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskProduct',
            new_name='TreatmentProduct',
        ),
    ]
