# Generated by Django 5.0.11 on 2025-04-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_rename_task_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AddField(
            model_name='treatment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
