# Generated by Django 5.0.11 on 2025-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0025_alter_treatment_options_treatment_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentproduct',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
