# Generated by Django 5.1.8 on 2025-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0027_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentproduct',
            name='price_per_ha',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='treatmentproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='treatmentproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
