# Generated by Django 5.1.8 on 2025-04-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0030_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
