# Generated by Django 5.1.8 on 2025-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='real_water_per_ha',
            field=models.IntegerField(blank=True, help_text='Mojado real usado por hectárea (en litros)', null=True),
        ),
    ]
