# Generated by Django 5.1.8 on 2025-04-29 14:07

from django.db import migrations


def set_real_water_per_ha(apps, schema_editor):
    Treatment = apps.get_model('farm', 'Treatment')
    for treatment in Treatment.objects.filter(status='completed'):
        treatment.real_water_per_ha = treatment.water_per_ha
        treatment.save()


def unset_real_water_per_ha(apps, schema_editor):
    Treatment = apps.get_model('farm', 'Treatment')
    for treatment in Treatment.objects.filter(status='completed'):
        treatment.real_water_per_ha = None
        treatment.save()


class Migration(migrations.Migration):
    dependencies = [
        ('farm', '0032_treatment_real_water_per_ha'),
    ]

    operations = [
        migrations.RunPython(set_real_water_per_ha, unset_real_water_per_ha),
    ]
