# Generated by Django 5.1.8 on 2025-05-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0035_alter_field_created_by_alter_field_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='field',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='treatmentproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatmentproduct',
            name='updated_by',
        ),
    ]
