# Generated by Django 5.1.8 on 2025-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0037_alter_treatmentproduct_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentproduct',
            name='dose',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='total_dose',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
