# Generated by Django 5.1.11 on 2025-07-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_user_options_user_last_activity_and_more'),
        ('farm', '0038_alter_treatmentproduct_dose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('labor', 'Mano de obra'), ('water', 'Recibo de agua'), ('irrigation_fee', 'Cuota comunidad de regantes'), ('machinery', 'Maquinaria'), ('fuel', 'Combustible'), ('maintenance', 'Mantenimiento'), ('fertilizer', 'Abonos no registrados'), ('seeds', 'Semillas'), ('other', 'Otros')], max_length=20, verbose_name='Tipo de gasto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('payment_date', models.DateField(verbose_name='Fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (€)')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='farm.field', verbose_name='Parcela')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
