# Generated by Django 5.1.11 on 2025-07-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_user_options_user_last_activity_and_more'),
        ('farm', '0039_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Tipo de gasto',
                'verbose_name_plural': 'Tipos de gasto',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='farm.expensetype', verbose_name='Tipo de gasto'),
        ),
    ]
