# Generated by Django 5.1.8 on 2025-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0042_finalize_expense_type_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spraying_dose_type',
            field=models.CharField(blank=True, choices=[('l_per_1000l', 'L/1000L'), ('kg_per_1000l', 'kg/1000L'), ('kg_per_ha', 'kg/ha'), ('l_per_ha', 'L/ha'), ('pct', '%')], max_length=20, null=True),
        ),
    ]
