# Generated by Django 5.1.8 on 2025-07-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0044_alter_field_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='fertigation_dose_type',
            field=models.CharField(blank=True, choices=[('l_per_ha', 'L/ha'), ('kg_per_ha', 'kg/ha')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='spraying_dose_type',
            field=models.CharField(blank=True, choices=[('l_per_1000l', 'L/1000L'), ('kg_per_1000l', 'kg/1000L'), ('kg_per_ha', 'kg/ha'), ('l_per_ha', 'L/ha'), ('pct', '%')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
