# Generated by Django 5.1.8 on 2025-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0045_alter_field_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fertigation_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spraying_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
