# Generated by Django 5.1.8 on 2025-07-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0046_alter_product_fertigation_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentproduct',
            name='dose',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
