# Generated by Django 5.1.8 on 2025-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0047_alter_treatmentproduct_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentproduct',
            name='total_dose',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
