# Generated by Django 5.1.8 on 2025-07-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0048_alter_treatmentproduct_total_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='calculation_mode',
            field=models.CharField(choices=[('total', 'Importe total'), ('quantity_price', 'Cantidad × Precio unitario'), ('price_per_ha', 'Precio por hectárea')], default='total', max_length=20, verbose_name='Modo de cálculo'),
        ),
        migrations.AddField(
            model_name='expense',
            name='price_per_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por hectárea (€/ha)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario (€)'),
        ),
    ]
