# Generated by Django 5.1.8 on 2025-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0049_expense_calculation_mode_expense_price_per_ha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='field_area_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hectáreas (snapshot)'),
        ),
    ]
