# Generated by Django 5.1.8 on 2025-12-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0050_expense_field_area_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='treatmentproduct',
            name='deleted_at',
        ),
    ]
