# Generated by Django 5.1.8 on 2026-02-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0051_remove_treatment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='harvest',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Hectáreas recolectadas (opcional)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='price_pending',
            field=models.BooleanField(default=False, help_text='Marcar si el precio de venta aún está pendiente'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='sale_price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio de venta por kg (opcional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='yield_kg_per_ha',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Rendimiento (kg/ha) calculado automáticamente', max_digits=12, null=True),
        ),
    ]
