# Generated by Django 5.1.8 on 2026-02-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0053_alter_product_fertigation_dose_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='area_ha',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='yield_kg_per_ha',
        ),
    ]
