# Generated by Django 5.1.8 on 2026-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0054_remove_harvest_area_ha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='sale_price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta por kg (opcional)', max_digits=10, null=True),
        ),
    ]
