# Generated by Django 5.1.8 on 2026-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0055_harvest_amount_integer_price_2decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentproduct',
            name='total_overridden',
            field=models.BooleanField(default=False),
        ),
    ]
