# Generated by Django 5.1.8 on 2026-02-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0056_treatmentproduct_total_overridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
