# Generated by Django 5.1.8 on 2026-03-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0057_alter_expensetype_description_alter_expensetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='geometry',
            field=models.TextField(blank=True, help_text='GeoJSON del contorno de la parcela'),
        ),
    ]
