# Generated by Django 5.1.8 on 2026-03-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0058_field_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='location',
        ),
    ]
