# Generated by Django 5.1.15 on 2026-04-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0060_add_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentproduct',
            options={'ordering': ['id']},
        ),
    ]
