# Generated by Django 5.1.15 on 2026-04-06 10:14

from django.db import migrations, models


def set_initial_positions(apps, schema_editor):
    """
    Asigna posiciones a los TreatmentProduct existentes ordenando por id
    dentro de cada tratamiento. Esto es lo mejor que podemos hacer con datos
    históricos, ya que el campo position no existía antes.
    """
    TreatmentProduct = apps.get_model('farm', 'TreatmentProduct')
    Treatment = apps.get_model('farm', 'Treatment')

    for treatment in Treatment.objects.all():
        products = TreatmentProduct.objects.filter(treatment=treatment).order_by('id')
        for position, tp in enumerate(products):
            TreatmentProduct.objects.filter(pk=tp.pk).update(position=position)


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0061_treatmentproduct_ordering_by_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentproduct',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='treatmentproduct',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_initial_positions, migrations.RunPython.noop),
    ]
