# Generated by Django 5.1.15 on 2026-05-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0062_treatmentproduct_add_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fertigation_dose',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='spraying_dose',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='dose',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='treatmentproduct',
            name='total_dose',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
