# Generated by Django 5.1.15 on 2026-05-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_preferences_channels'),
        ('farm', '0063_increase_dose_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactiva el producto para archivarlo sin eliminarlo', verbose_name='Activo'),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (€/ud.)')),
                ('effective_date', models.DateField(verbose_name='Fecha')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Notas')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='accounts.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='farm.product')),
            ],
            options={
                'verbose_name': 'Histórico de precio',
                'verbose_name_plural': 'Histórico de precios',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
