# Generated by Django 5.1.15 on 2026-05-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0064_product_is_active_price_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricehistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='productpricehistory',
            name='supplier',
        ),
    ]
