# Generated by Django 5.1.15 on 2026-05-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_preferences_channels'),
        ('farm', '0066_populate_initial_price_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='field',
            name='storage_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='farm.storagepoint', verbose_name='Casetilla'),
        ),
        migrations.AddConstraint(
            model_name='storagepoint',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_storage_point_per_org'),
        ),
    ]
