# Generated by Django 5.1.15 on 2026-07-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0068_treatment_applied_area_zone_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='zone_notes',
            field=models.CharField(blank=True, help_text="Zona o sector tratado (ej: 'zona norte', 'sector 3'). Opcional.", max_length=200),
        ),
    ]
