name: Actualización de estado de tratamientos
# Este workflow se ejecuta automáticamente a diario para actualizar los estados de los tratamientos en la base de datos.
# Solo procesa los datos de los últimos 3 días para ser más eficiente.
# También se puede ejecutar manualmente a través de GitHub Actions.
# La tarea se ejecuta con un entorno Python 3.12 y depende de las librerías especificadas en `requirements.txt`.

on:
  schedule:
    - cron: '5 0 * * *'  # cada día a las 00:05 UTC
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  update-tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run update command
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python manage.py update_task_status
